// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rubnqcfkfltqvktfvdcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1Ym5xY2ZrZmx0cXZrdGZ2ZGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMTY4MjYsImV4cCI6MjA1MjU5MjgyNn0.Xv6Xdf5orHtC-9pehLbVI52fQAPBIvsJJRiS-481hpY"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);