// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bakcfxydttumgdonncpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJha2NmeHlkdHR1bWdkb25uY3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxODIxNjQsImV4cCI6MjA4NTc1ODE2NH0.286-keVD-K2VidCggfmzGAPAlvnV9aSZ08V_9VRkkIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});